[project]
name = "sphere-station-simulations"
version = "0.1.0"
requires-python = ">=3.8"

[project.dependencies]
pandas = "*"
numpy = "*"
matplotlib = "*"
tqdm = "*"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
