name: GitBook Style Rename

on:
  push:
    branches: [main]

jobs:
  rename:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Rename files to GitBook style
        run: |
          python <<'PYTHON'
          import os, re, subprocess
          for root, dirs, files in os.walk('.', topdown=False):
              if root.startswith('./.git') or root.startswith('./simulations'):
                  continue
              for name in dirs + files:
                  if name.startswith('.git') or name.endswith('.py'):
                      continue
                  new = re.sub(r'[^a-z0-9.-]+', '-', name.lower())
                  if new != name:
                      subprocess.run(['git', 'mv', os.path.join(root, name), os.path.join(root, new)])
          PYTHON
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: rename files to gitbook style [skip ci]"
            git push
          fi
