name: Selective Publish to PDF

on:
  workflow_run:
    workflows: ["GitBook Style Rename"]
    types:
      - completed
  workflow_dispatch:

jobs:
  selective-publish:
    if: github.actor != 'github-actions[bot]' && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref }}

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Selective publish via tool
        run: |
            python .github/tools/publishing/publisher.py --use-summary

      - name: Commit and push generated PDFs
        if: steps.prep.outputs.should_publish == 'true'
        env:
          MANIFEST: ${{ steps.prep.outputs.manifest }}
        run: |
          if [ -n "$(git status --porcelain publish $MANIFEST)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add publish "$MANIFEST"
            git commit -m "chore: selective publish → PDF (auto)"
            git pull --rebase origin "${GITHUB_REF_NAME}"
            git push origin HEAD:"${GITHUB_REF_NAME}"
          else
            echo "No changes in publish or manifest — nothing to commit."
          fi
