name: Selective Publish to PDF

on:
  workflow_call:
    inputs:
      use_summary:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      use_summary:
        required: false
        type: boolean
        default: true

jobs:
  selective-publish:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Selective publish via tool
        id: prep
        run: |
            python .github/tools/publishing/publisher.py ${{ inputs.use_summary && '--use-summary' || '' }}

      - name: Commit and push generated PDFs
        if: steps.prep.outputs.built_count != '0'
        env:
          MANIFEST: ${{ steps.prep.outputs.manifest }}
        run: |
          if [ -n "$(git status --porcelain publish $MANIFEST)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add publish "$MANIFEST"
            git commit -m "chore: selective publish → PDF (auto)"
            git pull --rebase origin "${GITHUB_REF_NAME}"
            git push origin HEAD:"${GITHUB_REF_NAME}"
          else
            echo "No changes in publish or manifest — nothing to commit."
          fi
